out_tb_blue <- read.csv("~/Documents/jgeotec2020/tables/output_samples_blue.csv")
out_tb_green <- read.csv("~/Documents/jgeotec2020/tables/output_samples_green.csv")
out_tb_red <- read.csv("~/Documents/jgeotec2020/tables/output_samples_red.csv")
out_tb_nir <- read.csv("~/Documents/jgeotec2020/tables/output_samples_nir.csv")
out_tb_swir1 <- read.csv("~/Documents/jgeotec2020/tables/output_samples_swir1.csv")
out_tb_swir2 <- read.csv("~/Documents/jgeotec2020/tables/output_samples_swir2.csv")
out_tb_ndvi <- read.csv("~/Documents/jgeotec2020/tables/output_samples_ndvi.csv")
out_tb_ndwi <- read.csv("~/Documents/jgeotec2020/tables/output_samples_ndwi.csv")
out_tb_savi <- read.csv("~/Documents/jgeotec2020/tables/output_samples_savi.csv")
out_tb_ndmi <- read.csv("~/Documents/jgeotec2020/tables/output_samples_ndmi.csv")
out_tb_greenness <- read.csv("~/Documents/jgeotec2020/tables/output_samples_greenness.csv")
out_tb_wetness <- read.csv("~/Documents/jgeotec2020/tables/output_samples_wetness.csv")
out_tb_brightness <- read.csv("~/Documents/jgeotec2020/tables/output_samples_brightness.csv")

b_g <- merge(out_tb_blue, out_tb_green, key = "CID")
b_g_r <- merge(b_g, out_tb_red, key = "CID")
b_g_r_nir <- merge(b_g_r, out_tb_nir, key = "CID")
b_g <- merge(out_tb_blue, out_tb_green, key = "CID")
b_g <- merge(out_tb_blue, out_tb_green, key = "CID")
b_g <- merge(out_tb_blue, out_tb_green, key = "CID")
b_g <- merge(out_tb_blue, out_tb_green, key = "CID")
b_g <- merge(out_tb_blue, out_tb_green, key = "CID")
b_g <- merge(out_tb_blue, out_tb_green, key = "CID")
b_g <- merge(out_tb_blue, out_tb_green, key = "CID")
b_g <- merge(out_tb_blue, out_tb_green, key = "CID")
b_g <- merge(out_tb_blue, out_tb_green, key = "CID")
b_g <- merge(out_tb_blue, out_tb_green, key = "CID")
b_g <- merge(out_tb_blue, out_tb_green, key = "CID")
b_g <- merge(out_tb_blue, out_tb_green, key = "CID")



write.csv(b_g, "~/Documents/jgeotec2020/tables/output_samples_b_g.csv")
write.csv(b_g_r, "~/Documents/jgeotec2020/tables/output_samples_b_g_r.csv")
write.csv(b_g_r_nir, "~/Documents/jgeotec2020/tables/output_samples_b_g_r_nir.csv")
write.csv(b_g, "~/Documents/jgeotec2020/tables/output_samples_b_g.csv")
write.csv(b_g, "~/Documents/jgeotec2020/tables/output_samples_b_g.csv")
write.csv(b_g, "~/Documents/jgeotec2020/tables/output_samples_b_g.csv")
write.csv(b_g, "~/Documents/jgeotec2020/tables/output_samples_b_g.csv")
write.csv(b_g, "~/Documents/jgeotec2020/tables/output_samples_b_g.csv")
write.csv(b_g, "~/Documents/jgeotec2020/tables/output_samples_b_g.csv")